### ISSUE TITLE
WASM Median Cut

### ISSUE THREAD

**Issue by f-aguzzi** [studio-YOLO/editpix#17]
**Task:**
Implement a `rust` version of the `JavaScript` median cut algorithm for palette extraction, originally seen in the experimental `kMean` branch, so that it may be used for the `WebAssembly` module.

**State of this issue:**
- [x] code implemented in `lib/src/lib.rs`
- [x] `wasm` plugin and `js` boilerplate included in `src/core`
- [x] functionality exposed through `src/editpix.js`
- [x] fully functional and tested
